### ISSUE TITLE
java.lang.ClassCastException: com.squareup.moshi.LinkedHashTreeMap cannot be cast to ...

### ISSUE THREAD

**Issue by tenSunFree** [skydoves/GoldMovies#3]
**Please complete the following information:**

- Library Version [e.g. v1.0.0]
Answer︰同github上的，沒有修改過。

- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
Answer︰HTC U11 with Android 9.0
 
**Describe the Bug:**
Add a clear description about the problem.
Answer︰java.lang.ClassCastException: com.squareup.moshi.LinkedHashTreeMap cannot be cast to ...
![2020-01-06_185348](https://user-images.githubusercontent.com/23090085/71814570-c6c26b00-30b7-11ea-9305-8d8d758e7aa8.jpg)

**Expected Behavior:**
A clear description of what you expected to happen.
Answer︰點擊某部電影後，快速地按下返回鍵。然後再馬上點擊該部電影，再快速地按下返回鍵。快速地不斷的重複這個行為。

**Comment by skydoves** [comment]
@tenSunFree 
Hi, I reused the Gson converter instead of Moshi.
Thank you for your issue :)
