### ISSUE TITLE
Close response body

### ISSUE THREAD

**Issue by eliasbellido** [skydoves/GoldMovies#4]
Hi, I was reading the console log and found that whenever there's a bad response the following message shows up: 

`A connection to https://image.tmdb.org/ was leaked. Did you forget to close a response body?
`

Any workaround for that? I was digging a little and the solution is to close the body response on finally try catch on the ApiResponse.kt but I cannot get it to work.

Thanks in advance.

**Comment by skydoves** [comment]
@eliasbellido 
Hi, it seems to happen the `close()` or `string()` method is not called when failed requests.
I pushed a commit related to `close()` related to the failed requests.
Could you check the warning still happened?

**Comment by eliasbellido** [comment]
Yep it seems it's working just fine. Thanks man, I really appreciate your time and your code looks very nice (: 
감사합니다!
